### ISSUE TITLE
Mesh volume should not be divided by 1000

### ISSUE THREAD

**Issue by johncalvinyoung** [isalgadof/Three-volume#1]
This library currently computes the volume in cubic THREE.js units, and then divides by 1000. This results in a less useful volume, as many choices of units do not lend themselves to 10x division. I'd suggest removing the `1000` divisor and returning cubic units. Without this change, the library isn't particularly useful for my team.

**Comment by isalgadof** [comment]
Thank you for the feedback. Issue fixed on version 2.0.5, please update package.
