### ISSUE TITLE
errors when passing a `BufferGeometry` as argument

### ISSUE THREAD

**Issue by statusunknown418** [isalgadof/Three-volume#2]
I'm trying to use the lib but getting this error 
```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at calculateVolume (webpack-internal:///(rsc)/./node_modules/.pnpm/three-volume@2.0.5/node_modules/three-volume/index.js:10:29)
    at POST (webpack-internal:///(rsc)/./src/app/api/analyze/route.ts:29:85)
```

using this
```ts
import { NextResponse, type NextRequest } from "next/server";
import { Box3, Vector3 } from "three";
import { ThreeVolume } from "three-volume";
import { STLLoader } from "three/addons";

export const POST = async (req: NextRequest) => {
  const body = (await req.json()) as { url: string };

  if (!body.url) {
    return NextResponse.json({ error: "No url provided" }, { status: 400 });
  }

  const t1 = performance.now();
  const fileFetch = await fetch(body.url);
  const arrayBuffer = await fileFetch.arrayBuffer();

  const stlLoader = new STLLoader();

  const fileV3 = stlLoader.parse(arrayBuffer);
  const box = new Box3().setFromArray(fileV3.getAttribute("position").array);
  const size = new Vector3();
  const computedVolume = ThreeVolume(fileV3);
  const t2 = performance.now();

  return NextResponse.json(
    { help: true, dimensions: box.getSize(size), computedVolume, took: t2 - t1 },
    { status: 200 },
  );
};
```
is there any solution?

**Comment by isalgadof** [comment]
@statusunknown418 

1) Are you sure the file's arraybuffer is getting read properly? Have you tried `console.log('buffer:',arrayBuffer)` and validating it is properly parsed into a geometry with `console.log('isbuffer?,',fileV3.isBufferGeometry)`? Please attach output of both prints (please use a simple stl with low polygon count or the log will be infinitely long). 
If you use an .obj, you should access its geometry through: `const mesh = loader.parse(file).children[0].geometry;` instead.

2) Try updating your loader import for this one -which i've validated is working correctly: `import { STLLoader } from "three/examples/jsm/loaders/STLLoader";`  (it shouldn't matter but to be sure, maybe the general loader is in an incompatible version?). 

3) If problem persists, please attach the STL file into any file sharing page (idk if Github attach size limit is enough for you) and post the link here so i can test further.

**Comment by statusunknown418** [comment]
@isalgadof well the logs show no problem with the file itself (in any case that would be a bigger problem since I'm trying to create an API for STL files):
```
ArrayBuffer {
  [Uint8Contents]: <53 54 4c 42 20 41 54 46 20 31 32 2e 34 2e 30 2e 37 33 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 1c 00 00 00 00 00 80 3f 61 0b b6 24 00 00 00 00 00 00 34 c2 ... 1384 more bytes>,
  byteLength: 1484
} { isBuffer: true }
```
this is the file https://utfs.io/f/2a0f4600-0e0e-40fd-99a0-5204625dbea2-18dbsb.stl 

I did however found a solution by using a mesh like this

```ts
const fileV4 = stlLoader.parse(arrayBuffer);
const mesh = new Mesh(fileV4, new MeshBasicMaterial());
const volume2 = ThreeVolume(mesh as unknown as BufferGeometry); // notice the type-casting
```

if the lib is intended to work this way too, please consider adding support for those types

**Comment by isalgadof** [comment]
Thank you for confirming! 

I'll close this error since it wasn't an error with the module after all; and just update the Readme file to reference how to typecast so that other Mesh objects can be used in a manner similar to yours.

**Comment by makc** [comment]
I'm sorry,
```js
const mesh = new Mesh(fileV4, new MeshBasicMaterial());
mesh as unknown as BufferGeometry
```
what? if mesh is Mesh, it has nothing to do with BufferGeometry - how would this cast ever work?

**Comment by isalgadof** [comment]
> I'm sorry,
> 
> const mesh = new Mesh(fileV4, new MeshBasicMaterial());
> mesh as unknown as BufferGeometry
> what? if mesh is Mesh, it has nothing to do with BufferGeometry - how would this cast ever work?

If you look again, you'll find its not a direct cast but rather a double type assertion. The intermediate cast `as unknown` will avoid TS going crazy for an incompatible-in-paper-but-compatible-in-reality-cast being used.

Why? It will avoid problems with incompatible models that don't follow strictly the geometry.mesh buffer pattern and are direct meshes (STLLoader can return both geometry or meshes depending on the version and was inconsistent when testing).

Is it pretty?: Is anything objectively pretty?
Does it work?: Of course it works.
Could it be improved?: Absolutely. 
Will i put more hours of free labor for something that already works perfectly fine? Sure as hell i won't. 

But hey, feel free to contribute yourself and improve on it. I'll gladly review any PR you submit 😄
